# build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: HDF5 & Chunk Selection for Audio and Video
description: Tests on chunk selection for audio and video and its effect on access time and compression
